<a href="https://colab.research.google.com/github/TanweerMI/EDA_Labs/blob/main/EDA1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import numpy as np

In [17]:
dataFrame1=pd.DataFrame({"StudentID":[1,3,5,7,9],"Score":[89,39,50,97,22]})
dataFrame2=pd.DataFrame({"StudentID":[2,4,6,8,10],"Score":[98,93,44,77,69]})
vertical_concat=pd.concat([dataFrame1,dataFrame2],ignore_index=True)
print("Vertical Concatenation:\n",vertical_concat)

Vertical Concatenation:
    StudentID  Score
0          1     89
1          3     39
2          5     50
3          7     97
4          9     22
5          2     98
6          4     93
7          6     44
8          8     77
9         10     69

In [18]:
horizontal_concat=pd.concat([dataFrame1,dataFrame2],axis=1)
print("Horizontal Concatenation:\n",horizontal_concat)

Horizontal Concatenation:
    StudentID  Score  StudentID  Score
0          1     89          2     98
1          3     39          4     93
2          5     50          6     44
3          7     97          8     77
4          9     22         10     69

In [19]:
dfSE=pd.DataFrame({"StudentID":[2,4,6,8,10,12],"ScoreSE":[98,93,44,77,69,56]})
dfML=pd.DataFrame({"StudentID":[1,2,3,4,5,6,8,10],"ScoreML":[39,93,49,44,55,66,77,88]})
inner_join=pd.merge(dfSE,dfML,on="StudentID",how="inner")
print("\nInner join:\n",inner_join)

Inner join:
    StudentID  ScoreSE  ScoreML
0          2       98       93
1          4       93       44
2          6       44       66
3          8       77       77
4         10       69       88

In [20]:
left_join=pd.merge(dfSE,dfML,on="StudentID",how="left")
print("\\nLeft join:\n",left_join)

\nLeft join:
    StudentID  ScoreSE  ScoreML
0          2       98     93.0
1          4       93     44.0
2          6       44     66.0
3          8       77     77.0
4         10       69     88.0
5         12       56      NaN

In [21]:
right_join=pd.merge(dfSE,dfML,on="StudentID",how="right")
print("\nRight join:\n",right_join)

Right join:
    StudentID  ScoreSE  ScoreML
0          1      NaN       39
1          2     98.0       93
2          3      NaN       49
3          4     93.0       44
4          5      NaN       55
5          6     44.0       66
6          8     77.0       77
7         10     69.0       88

In [22]:
outer_join=pd.merge(dfSE,dfML,on="StudentID",how="inner")
print("\nOuter join:\n",outer_join)

Outer join:
    StudentID  ScoreSE  ScoreML
0          2       98       93
1          4       93       44
2          6       44       66
3          8       77       77
4         10       69       88

In [23]:
sales=pd.DataFrame({"Quantity":[100,250,300,150],"UnitPrice":[50,60,45,80]})
sales["TotalPrice"]=sales["Quantity"]*sales["UnitPrice"]
print("\nSales Data:\n",sales)

Sales Data:
    Quantity  UnitPrice  TotalPrice
0       100         50        5000
1       250         60       15000
2       300         45       13500
3       150         80       12000

In [24]:
print("\nDescriptive Statistics:")
print(sales.describe())

Descriptive Statistics:
         Quantity  UnitPrice    TotalPrice
count    4.000000    4.00000      4.000000
mean   200.000000   58.75000  11375.000000
std     91.287093   15.47848   4422.951503
min    100.000000   45.00000   5000.000000
25%    137.500000   48.75000  10250.000000
50%    200.000000   55.00000  12750.000000
75%    262.500000   65.00000  13875.000000
max    300.000000   80.00000  15000.000000

In [25]:
company_df=pd.DataFrame({"Company":["ABC","XYZ","ABC","PQR","XYZ","ABC"]})
print("\nCompany Counts:\n",company_df["Company"].value_counts())

Company Counts:
 Company
ABC    3
XYZ    2
PQR    1
Name: count, dtype: int64

In [26]:
data=np.arange(15).reshape((3,5))
dframe=pd.DataFrame(data,index=["Rainfall","Humanity","Wind"],columns=["Bergen","Oslo","Trodheim","Stavanger","Kristiansand"])
print("\nOriginal DataFrame:\n",dframe)

stacked=dframe.stack()
print("\nStacked Data:\n",stacked)

Original DataFrame:
           Bergen  Oslo  Trodheim  Stavanger  Kristiansand
Rainfall       0     1         2          3             4
Humanity       5     6         7          8             9
Wind          10    11        12         13            14

Stacked Data:
 Rainfall  Bergen           0
          Oslo             1
          Trodheim         2
          Stavanger        3
          Kristiansand     4
Humanity  Bergen           5
          Oslo             6
          Trodheim         7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trodheim        12
          Stavanger       13
          Kristiansand    14
dtype: int64

In [27]:
unstacked=stacked.unstack()
print("Unstacked data:\n",unstacked)

Unstacked data:
           Bergen  Oslo  Trodheim  Stavanger  Kristiansand
Rainfall       0     1         2          3             4
Humanity       5     6         7          8             9
Wind          10    11        12         13            14

In [28]:
series1=pd.Series([0, 111, 222, 333],index=['zeros', 'ones', 'twos', 'threes'])
series2=pd.Series([444, 555, 666],index=['fours', 'fives', 'sixs'])
frame=pd.concat([series1, series2],keys=['Number1', 'Number2'])
print("\nHierarchical Series:\n",frame)
print("\nUnstacked Series:\n",frame.unstack())

Hierarchical Series:
 Number1  zeros       0
         ones      111
         twos      222
         threes    333
Number2  fours     444
         fives     555
         sixs      666
dtype: int64

Unstacked Series:
          fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN

In [30]:
df=pd.read_csv("chess_games.csv")
df.head()

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
0,1,False,13,Out of Time,White,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,5,Slav Defense: Exchange Variation,Slav Defense,NaN,Exchange Variation
1,2,True,16,Resign,Black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,4,Nimzowitsch Defense: Kennedy Variation,Nimzowitsch Defense,NaN,Kennedy Variation
2,3,True,61,Mate,White,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,3,King's Pawn Game: Leonardis Variation,King's Pawn Game,NaN,Leonardis Variation
3,4,True,61,Mate,White,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,3,Queen's Pawn Game: Zukertort Variation,Queen's Pawn Game,NaN,Zukertort Variation
4,5,True,95,Mate,White,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,5,Philidor Defense,Philidor Defense,NaN,NaN

In [31]:
df.tail()

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
20053,20054,True,24,Resign,White,10+10,belcolt,1691,jamboger,1220,d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...,A80,2,Dutch Defense,Dutch Defense,NaN,NaN
20054,20055,True,82,Mate,Black,10+0,jamboger,1233,farrukhasomiddinov,1196,d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...,A41,2,Queen's Pawn,Queen's Pawn,NaN,NaN
20055,20056,True,35,Mate,White,10+0,jamboger,1219,schaaksmurf3,1286,d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack
20056,20057,True,109,Resign,White,10+0,marcodisogno,1360,jamboger,1227,e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...,B07,4,Pirc Defense,Pirc Defense,NaN,NaN
20057,20058,True,78,Mate,Black,10+0,jamboger,1235,ffbob,1339,d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack

In [34]:
df.shape

(20058, 17)

In [35]:
df.columns

Index(['game_id', 'rated', 'turns', 'victory_status', 'winner',
       'time_increment', 'white_id', 'white_rating', 'black_id',
       'black_rating', 'moves', 'opening_code', 'opening_moves',
       'opening_fullname', 'opening_shortname', 'opening_response',
       'opening_variation'],
      dtype='object')

In [36]:
df.dtypes

game_id               int64
rated                  bool
turns                 int64
victory_status       object
winner               object
time_increment       object
white_id             object
white_rating          int64
black_id             object
black_rating          int64
moves                object
opening_code         object
opening_moves         int64
opening_fullname     object
opening_shortname    object
opening_response     object
opening_variation    object
dtype: object

In [37]:
df.describe()

            game_id         turns  white_rating  black_rating  opening_moves
count  20058.000000  20058.000000  20058.000000  20058.000000   20058.000000
mean   10029.500000     60.465999   1596.631868   1588.831987       4.816981
std     5790.390185     33.570585    291.253376    291.036126       2.797152
min        1.000000      1.000000    784.000000    789.000000       1.000000
25%     5015.250000     37.000000   1398.000000   1391.000000       3.000000
50%    10029.500000     55.000000   1567.000000   1562.000000       4.000000
75%    15043.750000     79.000000   1793.000000   1784.000000       6.000000
max    20058.000000    349.000000   2700.000000   2723.000000      28.000000