<a href="https://colab.research.google.com/github/TanweerMI/EDA_Labs/blob/main/EDA_LAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1=pd.DataFrame({'Restaurant':['Mcd','KFC','Burger King','SFC','Subway','Jacks','Bubee'],'Sales in millions':[6,5,0.1,43,15,6.7,0.5]})
df2=pd.DataFrame({'Restaurant':['Hardees','Lakshmi caterers','Darling','Bubee','Jimmy John','Hatam','Albaik'],'Sales in millions':[14,22,9,0.5,0.78,22,1]})

In [ ]:
df=pd.concat([df1,df2],axis=1,ignore_index=True)
df

             0     1                 2      3
0          Mcd   6.0           Hardees  14.00
1          KFC   5.0  Lakshmi caterers  22.00
2  Burger King   0.1           Darling   9.00
3          SFC  43.0             Bubee   0.50
4       Subway  15.0        Jimmy John   0.78
5        Jacks   6.7             Hatam  22.00
6        Bubee   0.5            Albaik   1.00

In [ ]:
dfMerge=df1.merge(df2,how='inner')
dfMerge

  Restaurant  Sales in millions
0      Bubee                0.5

In [ ]:
dfMerge=df1.merge(df2,how='left')
dfMerge

    Restaurant  Sales in millions
0          Mcd                6.0
1          KFC                5.0
2  Burger King                0.1
3          SFC               43.0
4       Subway               15.0
5        Jacks                6.7
6        Bubee                0.5

In [ ]:
dfMerge=df1.merge(df2,how='right')
dfMerge

         Restaurant  Sales in millions
0           Hardees              14.00
1  Lakshmi caterers              22.00
2           Darling               9.00
3             Bubee               0.50
4        Jimmy John               0.78
5             Hatam              22.00
6            Albaik               1.00

In [ ]:
data=np.arange(24).reshape(6,4)
indexers=[2006,2010,2014,2018,2022,2026]
dframe=pd.DataFrame(data,index=indexers,columns=['Messi','Ronaldo','Mbappe','Neymar'])
dframe

      Messi  Ronaldo  Mbappe  Neymar
2006      0        1       2       3
2010      4        5       6       7
2014      8        9      10      11
2018     12       13      14      15
2022     16       17      18      19
2026     20       21      22      23

In [ ]:
stacked=dframe.stack()
stacked

2006  Messi       0
      Ronaldo     1
      Mbappe      2
      Neymar      3
2010  Messi       4
      Ronaldo     5
      Mbappe      6
      Neymar      7
2014  Messi       8
      Ronaldo     9
      Mbappe     10
      Neymar     11
2018  Messi      12
      Ronaldo    13
      Mbappe     14
      Neymar     15
2022  Messi      16
      Ronaldo    17
      Mbappe     18
      Neymar     19
2026  Messi      20
      Ronaldo    21
      Mbappe     22
      Neymar     23
dtype: int64

In [ ]:
series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])
frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])

zeros       0
ones      111
twos      222
threes    333
dtype: int64