In [ ]:
import pandas as pd
import numpy as np

data=np.arange(30,42).reshape(4,3)
dfx=pd.DataFrame(data,index=['Messi','Ronaldo','No','Mbappe'],columns=['quadrant1','quadrant2','quadrant3'])
dfx

         quadrant1  quadrant2  quadrant3
Messi           30         31         32
Ronaldo         33         34         35
No              36         37         38
Mbappe          39         40         41

In [ ]:
dfx['quadrant4']=np.nan
dfx.loc['Mbappe']=np.arange(39,43)
dfx.loc['No']=np.nan
dfx['quadrant5']=np.nan
dfx['quadrant5']['Ronaldo']=46
dfx

/tmp/ipykernel_1693/3921901518.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['quadrant5']['Ronaldo']=46

         quadrant1  quadrant2  quadrant3  quadrant4  quadrant5
Messi         30.0       31.0       32.0        NaN        NaN
Ronaldo       33.0       34.0       35.0        NaN       46.0
No             NaN        NaN        NaN        NaN        NaN
Mbappe        39.0       40.0       41.0       42.0        NaN

In [ ]:
dfx.isnull()

         quadrant1  quadrant2  quadrant3  quadrant4  quadrant5
Messi        False      False      False       True       True
Ronaldo      False      False      False       True      False
No            True       True       True       True       True
Mbappe       False      False      False      False       True

In [ ]:
dfx.notnull()

         quadrant1  quadrant2  quadrant3  quadrant4  quadrant5
Messi         True       True       True      False      False
Ronaldo       True       True       True      False       True
No           False      False      False      False      False
Mbappe        True       True       True       True      False

In [ ]:
dfx.isnull().sum()

quadrant1    1
quadrant2    1
quadrant3    1
quadrant4    3
quadrant5    3
dtype: int64

In [ ]:
dfx.isnull().sum().sum()

np.int64(9)

In [ ]:
dfx.count()

quadrant1    3
quadrant2    3
quadrant3    3
quadrant4    1
quadrant5    1
dtype: int64

In [ ]:
dfx.notnull().sum()

quadrant1    3
quadrant2    3
quadrant3    3
quadrant4    1
quadrant5    1
dtype: int64

In [ ]:
dfx.quadrant4[dfx.quadrant4.notnull()]

Mbappe    42.0
Name: quadrant4, dtype: float64

In [ ]:
dfx.quadrant4.dropna()

Mbappe    42.0
Name: quadrant4, dtype: float64

In [ ]:
dfx.dropna()

Empty DataFrame
Columns: [quadrant1, quadrant2, quadrant3, quadrant4, quadrant5]
Index: []

In [ ]:
dfx.dropna(how='all')

         quadrant1  quadrant2  quadrant3  quadrant4  quadrant5
Messi         30.0       31.0       32.0        NaN        NaN
Ronaldo       33.0       34.0       35.0        NaN       46.0
Mbappe        39.0       40.0       41.0       42.0        NaN

In [ ]:
dfx.dropna(how='all',axis=1)

         quadrant1  quadrant2  quadrant3  quadrant4  quadrant5
Messi         30.0       31.0       32.0        NaN        NaN
Ronaldo       33.0       34.0       35.0        NaN       46.0
No             NaN        NaN        NaN        NaN        NaN
Mbappe        39.0       40.0       41.0       42.0        NaN

In [ ]:
dfx.dropna(thresh=3,axis=1)

         quadrant1  quadrant2  quadrant3
Messi         30.0       31.0       32.0
Ronaldo       33.0       34.0       35.0
No             NaN        NaN        NaN
Mbappe        39.0       40.0       41.0

In [ ]:
ar1 = np.array([100, 200, np.nan, 300])
ser1 = pd.Series(ar1)
ar1.mean(), ser1.mean()

(np.float64(nan), np.float64(200.0))

In [ ]:
ser2 = dfx.quadrant4
ser2.sum()

np.float64(42.0)

In [ ]:
ser2.mean()

np.float64(42.0)

In [ ]:
ser2.cumsum()

Messi       NaN
Ronaldo     NaN
No          NaN
Mbappe     42.0
Name: quadrant4, dtype: float64

In [ ]:
filledDf = dfx.fillna(0)
filledDf

         quadrant1  quadrant2  quadrant3  quadrant4  quadrant5
Messi         30.0       31.0       32.0        0.0        0.0
Ronaldo       33.0       34.0       35.0        0.0       46.0
No             0.0        0.0        0.0        0.0        0.0
Mbappe        39.0       40.0       41.0       42.0        0.0

In [ ]:
dfx.mean()

quadrant1    34.0
quadrant2    35.0
quadrant3    36.0
quadrant4    42.0
quadrant5    46.0
dtype: float64

In [ ]:
filledDf.mean()

quadrant1    25.50
quadrant2    26.25
quadrant3    27.00
quadrant4    10.50
quadrant5    11.50
dtype: float64

In [ ]:
dfx.quadrant4.fillna(method='ffill')

/tmp/ipykernel_1693/629965648.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.quadrant4.fillna(method='ffill')

Messi       NaN
Ronaldo     NaN
No          NaN
Mbappe     42.0
Name: quadrant4, dtype: float64

In [ ]:
dfx.quadrant4.fillna(method='bfill')

/tmp/ipykernel_1693/593866853.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.quadrant4.fillna(method='bfill')

Messi      42.0
Ronaldo    42.0
No         42.0
Mbappe     42.0
Name: quadrant4, dtype: float64

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

In [ ]:
df = pd.DataFrame(
 {
 "Age": [25, np.nan, 30, 45, 22],
 "Salary": [50000, 60000, np.nan, 80000, 45000],
 "Category": ["A", "B", "A", np.nan, "B"],
 }
)
df

    Age   Salary Category
0  25.0  50000.0        A
1   NaN  60000.0        B
2  30.0      NaN        A
3  45.0  80000.0      NaN
4  22.0  45000.0        B

In [ ]:
mean_imputer = SimpleImputer(strategy="mean")
df["Age_Mean"] = mean_imputer.fit_transform(df[["Age"]])
df

    Age   Salary Category  Age_Mean  Salary_Median
0  25.0  50000.0        A      25.0        50000.0
1   NaN  60000.0        B      30.5        60000.0
2  30.0      NaN        A      30.0        55000.0
3  45.0  80000.0      NaN      45.0        80000.0
4  22.0  45000.0        B      22.0        45000.0

In [ ]:
median_imputer = SimpleImputer(strategy="median")
df["Salary_Median"] = median_imputer.fit_transform(df[["Salary"]])
df

    Age   Salary Category  Salary_Median
0  25.0  50000.0        A        50000.0
1   NaN  60000.0        B        60000.0
2  30.0      NaN        A        55000.0
3  45.0  80000.0      NaN        80000.0
4  22.0  45000.0        B        45000.0

In [ ]:
mode_imputer = SimpleImputer(strategy="most_frequent")
df["Category_Mode"] = mode_imputer.fit_transform(df[["Category"]]).ravel()
df

,Age,Salary,Category,Salary_Median,Age_MICE,Salary_MICE,Category_Mode
0,25.0,50000.0,A,50000.0,25.000000,50000.000000,A
1,NaN,60000.0,B,60000.0,31.766487,60000.000000,B
2,30.0,NaN,A,55000.0,30.000000,57324.583367,A
3,45.0,80000.0,NaN,80000.0,45.000000,80000.000000,A
4,22.0,45000.0,B,45000.0,22.000000,45000.000000,B

In [ ]:
num_cols = ["Age", "Salary"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:,:] = mice_imputer.fit_transform(df_mice)
df["Age_MICE"] = df_mice["Age"]
df["Salary_MICE"] = df_mice["Salary"]
print(df)

    Age   Salary Category  Salary_Median   Age_MICE   Salary_MICE  \
0  25.0  50000.0        A        50000.0  25.000000  50000.000000
1   NaN  60000.0        B        60000.0  31.766487  60000.000000
2  30.0      NaN        A        55000.0  30.000000  57324.583367
3  45.0  80000.0      NaN        80000.0  45.000000  80000.000000
4  22.0  45000.0        B        45000.0  22.000000  45000.000000

  Category_Mode
0             A
1             B
2             A
3             A
4             B